FROM python:3.9-slim
ENV TZ="America/Santiago"

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./config .
COPY ./scheduler .

CMD ["python","app.py"]