FROM python:3.9-slim
ENV TZ="America/Santiago"

WORKDIR /usr/src/app

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000

COPY ./config .
COPY ./web_server .

CMD ["flask", "run"]